# Generated by Django 3.1.7 on 2021-04-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='gpa',
            field=models.FloatField(),
        ),
    ]
