# Generated by Django 3.1.7 on 2021-04-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210426_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courseinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.IntegerField()),
                ('coursetitle', models.CharField(max_length=500)),
                ('coursename', models.CharField(max_length=500)),
                ('sectionid', models.IntegerField()),
                ('coursedepartment', models.CharField(max_length=500)),
                ('instructorname', models.CharField(max_length=500)),
            ],
        ),
    ]
