# Generated by Django 3.1.7 on 2021-04-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_courseinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboardinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avgGpa', models.FloatField()),
            ],
        ),
    ]
