# Generated by Django 3.1.7 on 2021-04-27 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_dashboardinfo_totalseniors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboardinfo',
            old_name='totalseniors',
            new_name='totalIT',
        ),
    ]
