# Generated by Django 3.1.7 on 2021-04-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20210427_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardinfo',
            name='totalchem',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dashboardinfo',
            name='totalmarketing',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dashboardinfo',
            name='totalphysics',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dashboardinfo',
            name='totalstats',
            field=models.FloatField(default=0),
        ),
    ]
