# Generated by Django 3.1.7 on 2021-05-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20210427_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollmentinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=500)),
            ],
        ),
    ]
